harnessApiVersion: '1.0'
type: BUILD
notificationRules:
- conditions:
  - FAILED
  - SUCCESS
  - PAUSED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - 5m6u5QraQ5uhvmL5ik7O6A
phases:
- daemonSet: false
  name: Phase 1
  phaseSteps:
  - type: PREPARE_STEPS
    name: Prepare Steps
    steps:
    - type: APPROVAL
      name: Approval
      properties:
        approvalStateType: USER_GROUP
        templateUuid: null
        templateVariables: null
        templateVersion: null
        timeoutMillis: 86400000
        userGroups:
        - 5m6u5QraQ5uhvmL5ik7O6A
    stepsInParallel: false
  - type: COLLECT_ARTIFACT
    name: Collect Artifact
    stepsInParallel: false
  - type: WRAP_UP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  statefulSet: false
templatized: false
